FROM n8nio/n8n:latest

# Switch to root to install extra packages if needed
USER root

# (Optional) Install Python if you plan to use it later
# RUN apk add --update python3 py3-pip

# Switch back to node user
USER node